# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

## Using NumPy

In [1]:
import numpy as np

# Numpy Arrays

 Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but a matrix can still have only one row or one column).

## Creating NumPy Arrays

### From a Python List

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods to generate Arrays

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [10]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

## eye

Creates an identity matrix

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [11]:
np.random.rand(5)

array([0.29278458, 0.82014388, 0.79270855, 0.00845435, 0.24446504])

In [12]:
np.random.rand(1,5)

array([[0.9907678 , 0.43566891, 0.49303789, 0.55887972, 0.25328125]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [13]:
np.random.randn(2)

array([ 0.06059119, -0.77442361])

In [14]:
np.random.randn(5,10)

array([[-0.50681572, -0.02178192, -0.512757  , -2.37098201,  0.9822334 ,
        -0.02645606, -1.66416773,  0.38106291,  2.63142685,  0.82810687],
       [ 1.90561373, -0.7448762 , -0.51270314, -0.65170728,  0.35559374,
        -0.74526069,  0.91853043, -1.03827741, -1.03678782, -0.1058898 ],
       [ 0.77233819,  1.51362091,  1.28259489, -0.1694197 ,  0.94720015,
        -0.20479578, -0.57162844, -0.7869091 ,  0.54856197, -0.41401141],
       [ 0.94914764, -1.02172045, -1.40694033,  1.32084767, -0.75092731,
         0.624939  ,  0.66027381, -0.33214791, -0.67169608, -0.59844032],
       [ 0.07056154,  1.53666911, -0.72329388, -0.150136  , -0.78588787,
        -0.87162919, -0.08471903, -0.71744666, -0.23944544,  0.66497368]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [15]:
np.random.randint(1,10)

5

In [21]:
np.random.randint(1,2,10)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [22]:
ranarr = np.arange(1,15)

In [23]:
ranarr.max()

14

In [24]:
ranarr.min()

1

In [26]:
ranarr.argmax()

13

## Shape

Shape is an attribute that arrays have (not a method):

In [28]:
ranarr.shape

(14,)

In [34]:
ranarr.reshape(1,14)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

### dtype

You can also grab the data type of the object in the array:

In [35]:
ranarr.dtype

dtype('int64')