# NumPy Exercises 

#### Import NumPy as np

In [4]:
import numpy as np

#### Create an array of 10 zeros 

In [5]:
arr = np.random.randint(0,1,10)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of 10 ones

In [7]:
arr_ones = np.random.randint(1,2,10)
arr_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### Create an array of 10 fives

In [9]:
arr_fives = np.random.randint(5,6,10)
arr_fives

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [14]:
arr_50 = np.arange(10,51,1)
arr_50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [21]:
arr_50_even = np.arange(10,51,2)
arr_50_even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
matrix_3d = np.arange(0,9,1).reshape(3,3)
matrix_3d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [26]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [31]:
np.random.rand(1)

array([0.64079889])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [34]:
np.random.randn(25)

array([-0.98510484,  1.05868009,  0.62442077,  0.03824513, -1.03443168,
       -0.8706685 , -0.12526889,  0.62810839, -0.38957793,  0.62253159,
        1.22326021,  1.18231394, -1.97163173,  2.09395421,  0.10811048,
       -0.23029953,  1.32861143,  1.54068386,  1.13932212, -0.02326918,
       -0.25774925, -0.93162092,  0.65075646,  0.80082725, -0.83323823])

## Numpy Indexing and Selection

In [35]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [36]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [42]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [47]:
mat[3,4]

20

In [55]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [56]:
mat[4]

array([21, 22, 23, 24, 25])

In [58]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [59]:
mat.sum()

325

In [61]:
np.std(mat)

7.211102550927978

In [63]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])