# Numpy
This are the topics coverd in this version of the course

In [1]:
import numpy as np

In [2]:
my_array = np.array([3, 33.3, 3.1])

In [3]:
my_array

array([ 3. , 33.3,  3.1])

In [4]:
my_string_array = np.array(['Hola','Enrique','how','are','you'])

In [5]:
print(type(my_array))

<class 'numpy.ndarray'>


In [6]:
print(type(my_string_array))

<class 'numpy.ndarray'>


In [7]:
my_string_array.shape

(5,)

You can access the elements of an array just like you do it on a list

In [15]:
my_string_array[0]

'Hola'

In [18]:
len(my_string_array)

5

#How to create a two dimentional array

In [24]:
my_2d_array = np.array([[1,2],[3,4]])

(2, 2)

# Lets create some randoms

In [8]:
my_rands = np.random.randn(3,5)

In [9]:
my_rands

array([[-0.16282997, -0.43329944,  1.07319613, -0.28771894,  1.61121923],
       [-0.41148813, -0.82050608,  0.64398462, -0.95667724,  0.65685763],
       [-0.81954434,  0.41961436, -0.56393149, -1.01597461, -1.76843188]])

In [10]:
#Summing the rows
my_rands.sum(axis=1)

array([ 1.80056701, -0.8878292 , -3.74826796])

In [40]:
-0.13286365 + 0.07888391 + 0.13066627 -0.2493364 + 1.27252105

1.0998711799999998

In [49]:
# Summing columns of a particular ndarray
my_rands[:,0:2].sum(axis=0)

array([ 0.01019475, -0.06218364])

In [52]:
my_rands.sort()

In [53]:
my_rands

array([[-0.2493364 , -0.13286365,  0.07888391,  0.13066627,  1.27252105],
       [-1.01454059, -0.44982485, -0.01788819,  0.14410415,  1.04295126],
       [-1.07745716, -0.89989285, -0.61330955,  0.87347304,  1.56602604]])

### How about sorting strings

In [54]:
my_string_array

array(['Hola', 'Enrique', 'how', 'are', 'you'], dtype='<U7')

In [55]:
my_string_array.sort()

In [56]:
my_string_array

array(['Enrique', 'Hola', 'are', 'how', 'you'], dtype='<U7')

## Numpy: ndarray boolean indexing

In [14]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above fo

In [19]:
my_new_array = np.random.randint(low=-10,high=10,size=100)

In [22]:
my_new_array

array([  1,  -6,  -3,   5,   5,  -5,  -7,   3,   8,  -4, -10,   2,  -6,
         0,  -5,   7,   9,   9,   0,   5, -10, -10,   0,   0,  -3,  -8,
         5,  -6,   8,   7,  -2,   8,  -9,   8,   5,  -2,  -4,   2, -10,
         3,  -7,   6,  -9,  -6,  -8,  -6, -10,   4,  -8,   9,   4,   4,
        -4, -10,   7,   5,  -6,   1,   2,   1,  -5,  -7,  -5,   4,   2,
        -4,   6,  -5,   0,   7,  -9,   4,   4,  -3,   3,   6,  -9,  -9,
       -10,  -3,   5,   0,  -6,  -2,   6, -10,  -5,   3,  -5,  -1,   5,
         4,  -4,   2,   7,  -4,   3,  -5,  -8,  -5])

In [46]:
sorted_my_new = my_new_array[(my_new_array>=0) & (my_new_array<=5)]

In [49]:
sorted_my_new.sort()

### Operations

In [50]:
#sum 
np.sum(my_new_array)

-94

In [51]:
#multiply
np.multiply(my_new_array, 2)

array([  2, -12,  -6,  10,  10, -10, -14,   6,  16,  -8, -20,   4, -12,
         0, -10,  14,  18,  18,   0,  10, -20, -20,   0,   0,  -6, -16,
        10, -12,  16,  14,  -4,  16, -18,  16,  10,  -4,  -8,   4, -20,
         6, -14,  12, -18, -12, -16, -12, -20,   8, -16,  18,   8,   8,
        -8, -20,  14,  10, -12,   2,   4,   2, -10, -14, -10,   8,   4,
        -8,  12, -10,   0,  14, -18,   8,   8,  -6,   6,  12, -18, -18,
       -20,  -6,  10,   0, -12,  -4,  12, -20, -10,   6, -10,  -2,  10,
         8,  -8,   4,  14,  -8,   6, -10, -16, -10])

In [53]:
#Sqrt
np.sqrt(my_new_array[my_new_array>=0])

array([1.        , 2.23606798, 2.23606798, 1.73205081, 2.82842712,
       1.41421356, 0.        , 2.64575131, 3.        , 3.        ,
       0.        , 2.23606798, 0.        , 0.        , 2.23606798,
       2.82842712, 2.64575131, 2.82842712, 2.82842712, 2.23606798,
       1.41421356, 1.73205081, 2.44948974, 2.        , 3.        ,
       2.        , 2.        , 2.64575131, 2.23606798, 1.        ,
       1.41421356, 1.        , 2.        , 1.41421356, 2.44948974,
       0.        , 2.64575131, 2.        , 2.        , 1.73205081,
       2.44948974, 2.23606798, 0.        , 2.44948974, 1.73205081,
       2.23606798, 2.        , 1.41421356, 2.64575131, 1.73205081])

In [54]:
#exponent
np.exp(my_new_array)

array([2.71828183e+00, 2.47875218e-03, 4.97870684e-02, 1.48413159e+02,
       1.48413159e+02, 6.73794700e-03, 9.11881966e-04, 2.00855369e+01,
       2.98095799e+03, 1.83156389e-02, 4.53999298e-05, 7.38905610e+00,
       2.47875218e-03, 1.00000000e+00, 6.73794700e-03, 1.09663316e+03,
       8.10308393e+03, 8.10308393e+03, 1.00000000e+00, 1.48413159e+02,
       4.53999298e-05, 4.53999298e-05, 1.00000000e+00, 1.00000000e+00,
       4.97870684e-02, 3.35462628e-04, 1.48413159e+02, 2.47875218e-03,
       2.98095799e+03, 1.09663316e+03, 1.35335283e-01, 2.98095799e+03,
       1.23409804e-04, 2.98095799e+03, 1.48413159e+02, 1.35335283e-01,
       1.83156389e-02, 7.38905610e+00, 4.53999298e-05, 2.00855369e+01,
       9.11881966e-04, 4.03428793e+02, 1.23409804e-04, 2.47875218e-03,
       3.35462628e-04, 2.47875218e-03, 4.53999298e-05, 5.45981500e+01,
       3.35462628e-04, 8.10308393e+03, 5.45981500e+01, 5.45981500e+01,
       1.83156389e-02, 4.53999298e-05, 1.09663316e+03, 1.48413159e+02,
      

## Statistical methods, sorting and setting

In [56]:
#Lets create a 2x4 matrix
arr = 10*np.random.randn(2,4)

In [61]:
arr

array([[  3.29539392,  15.09582133,  -2.57331292,  -6.69233236],
       [ 27.79210156, -14.91185353,  15.02097765,  -7.20191806]])

In [71]:
#Get the mean of each row slicing the array
arr[:,1:3].mean(axis=1)

array([6.2612542 , 0.05456206])

In [72]:
#Lets get the mean of each column
arr.mean(axis=0)

array([15.54374774,  0.0919839 ,  6.22383237, -6.94712521])