# NumPy Indexing and Selection

In [1]:
import numpy as np

In [2]:
# Creating a sample array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [5]:
# Get a value at an index
arr[0]

0

In [6]:
# Slicing
arr[2:5]

array([2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [7]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

Note: While copying data is not copied, it is a view of the original array! To avoid memory problems use a hard copy

In [8]:
arr_copy = arr.copy()
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [11]:
arr_2d = np.array(([1,2,3],[4,5,6],[7,8,9])) #Notice the two brakets
# Show
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# Indexing a row
arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# Indexing rows and columns
arr_2d[:2,:1]

array([[1],
       [4]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [23]:
bool_arr = arr>20

In [24]:
bool_arr

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False])

In [25]:
arr[bool_arr]

array([100, 100, 100, 100, 100])

In [26]:
arr[arr>20]

array([100, 100, 100, 100, 100])